### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by smorabit** [theislab/scCODA#20]
Hi, I am excited to use scCODA for my data analysis, however I am running into an issue. I am following the [getting started tutorial notebook](https://github.com/theislab/scCODA/blob/master/tutorials/getting_started.ipynb), and I get a segmentation fault when I run this line:

```
sim_results = model_salm.sample_hmc()
```

I am suspicious that I didn't install scCODA properly? I followed the guidelines as posted on the github repo for installation (fresh conda environment, Python 3.8.5). I noticed that on the scCODA github, it specifically mentioned `tensorflow==2.3.2` as the version but after pip installing scCODA, I noticed that the version was `2.4.1`.

**Comment by johannesostner** [comment]
Hi!
Thanks for pointing this out, this is an oversight on my side. I am aware of the segfaults occurring with `tensorflow==2.4.x` and am working on fixing this.

Unfortunately, `tensorflow 2.4` was released after the last release of `scCODA`. I hotfixed the tensorflow version on github, but did not release a hotfix on PyPi. For now, I'd advise you to manually downgrade the tensorflow version via

`pip uninstall tensorflow`, then
`pip install tensorflow==2.3.2`.

I will also update the PyPi version, so reinstalling `scCODA` via PyPi should work as well

I hope this fixes the Issue for you. Sorry for the inconveniences caused by this.
