### ISSUE TITLE
Add scikit-bio as dependecies

### ISSUE THREAD

**Issue by b-schubert** [theislab/scCODA#22]

**Comment by johannesostner** [comment]
Due to some installation issues with the current version of scikit-bio in environments where numpy is not installed (see  https://github.com/biocore/scikit-bio/pull/1690).
Therefore, we recommend to install scikit-bio manually after installing scCODA by running `pip install scikit-bio`. 
Not having scikit-bio installed is also not an issue for using the main functionality of scCODA. It is only needed when using `sccoda.utils.other_models`
