### ISSUE TITLE
how to make one condition as a reference

### ISSUE THREAD

**Issue by FADHLyemen** [theislab/scCODA#24]
Hi,
In the notebook:
https://github.com/theislab/scCODA/blob/master/docs/source/getting_started.ipynb

the log fold change is control vs disease, but what if I have cond 1 and cond2, how to make one of them as a reference, so we can easily interpret the sign of fold change?

**Comment by johannesostner** [comment]
Hi!
The reference in scCODA is not referring to a condition, but rather a cell type. This is necessary, since single-cell sequencing population data is compositional, meaning we can only interpret changes with respect to a fixed reference category.

From what you describe, I assume you have one covariate (column in `data.obs`, let's call it `obs1`) with values `cond1` and `cond2`, and you want to compare these groups. To set e.g. `cond1` as the "control" group, you can modify the model formula to `"C(obs1, Treatment('cond1'))"`. Otherwise, simply the value from the first sample in your data is taken as the control. See also the advanced tutorial (https://github.com/theislab/scCODA/blob/master/tutorials/Modeling_options_and_result_analysis.ipynb) for an example.

**Comment by FADHLyemen** [comment]
thank you, that helps
