### ISSUE TITLE
How to approach inference on data with multiple timepoints

### ISSUE THREAD

**Issue by fbrundu** [theislab/scCODA#31]
Hi,

I wonder if you have any suggestion on how to sample on data with multiple timepoints.
I am running it now by using timepoint as an additional covariate, however, I was trying to understand if it would be more correct to run a different model for each timepoint.
I am currently testing the model "condition + timepoint". The reason I used all data (multiple timepoints) was that I thought it might help and speed up the inference.

Thanks!

**Comment by johannesostner** [comment]
Hi!

The formula parameter and the resulting design matrix in scCODA work in the same way as a linear model. By setting the time as one covariate, scCODA will check for linear effects over time on your cell population. This might not be flexible enough, though, since time series data is usually correlated within itself and exhibits nonlinear patterns. scCODA can not take this into account currently.

Therefore, I'd use one of two approaches that are possible with the current state of scCODA:
- If you are only interested in the influence of your condition at a certain time point, you should subset the data for each time point, and run scCODA with only the condition.
- If you also want to infer changes from one time point to another, you can use a subset of your data that includes only two time points and run scCODA on `condition + timepoint`.

I know that this might be tedious for data with many different time points, but there is currently no other way to use scCODA in its current state with such data that I can recommend.

**Comment by fbrundu** [comment]
Thanks for the explanation. It makes sense.
