### ISSUE TITLE
Result reproducibility issues depending on Python version

### ISSUE THREAD

**Issue by Christophe29-BZH** [theislab/scCODA#37]
Hello,

With an other member of my lab, we are starting to use scCODA for some analysis. We have encountered some puzzling results.
Here is the extended summary for a run in **python 3.8.11**, using "Undef" as the reference cell type:

![image](https://user-images.githubusercontent.com/52576175/130075613-c2f0b047-6be4-446e-b6ac-ebb0ca94ef62.png)

As you can see, according to the summary it looks like that only B-cells present a significant difference in proportion. However, the credible_effects report states that there is a difference for Granulocytes too.

Now, if we repeat the analysis in a **python 3.9.6** environment:

![image](https://user-images.githubusercontent.com/52576175/130077764-bc879088-3d7f-41ba-a1d9-636c858df06d.png)

This time, what is reported in the summary and the credible_effects reports seems consistent. You can also note the difference of running time.

So, I was wondering which of these results should I trust ? 
We also noticed that in Python3.9.6, the plot to look for a reference cell type is broken ( AttributeError: module 'sccoda.util.data_visualization' has no attribute 'rel_abundance_dispersion_plot' ) and it is not possible to run mod.CompositionalAnalysis() in automatic mode for the selection of the reference cell type ( TypeError: '<' not supported between instances of 'str' and 'int' )

In case this problem is data-dependent, here is the input table:
[Input_scCODA.csv](https://github.com/theislab/scCODA/files/7014632/Input_scCODA.csv)

If that's linked to an installation problem, I usually use conda environments:
- creating a new environment with the desired python version
- conda install -c conda-forge notebook
- pip install sccoda

Thank you for the help and feedback !

**Comment by johannesostner** [comment]
Hi! Thanks for the detailed description of your problem!

The inconsistency between the summary and the output from `credible_effects` was due to a bug in the `credible_effects` function. I could fortunately fix that on the master branch in github already.

As for the difference between the Python versions, there seem to be multiple issues here. The current version of scCODA was developed in Python 3.8, so I recommend to use that version for now. The next update of scCODA will be up-to-date again with the current versions of most dependencies. 
For that, I'd like to understand the problems you were facing in your Python 3.9 environment a little better. It would be incredible if you could tell me 

- The package versions of scCODA's dependencies that you have installed (especially tensorflow, tensorflow-probability, numpy, pandas, sccoda)
- The full error log you get when trying to run `mod.CompositionalAnalysis()`

Thanks in advance!

**Comment by Christophe29-BZH** [comment]
Thanks for the quick answer !
Indeed, installing with git has solved the problem for Python3.8

Here are the logs for Python 3.9:
![image](https://user-images.githubusercontent.com/52576175/130099578-7acc32ce-f6e5-4101-ab51-2caaa688f7d9.png)

And the list of the dependencies installed with conda for Python3.9:
[Dependencies_conda_Py3.9.csv](https://github.com/theislab/scCODA/files/7015784/Dependencies_conda_Py3.9.csv)

Hope that helps you. You can reach me if you need anything else.

**Comment by johannesostner** [comment]
I just released a new update of scCODA (0.1.4) that now supports the latest versions of tensorflow (you had tensorflow 2.6 installed in your 3.9 environment). Running it in Python 3.9 should also be possible.
This hopefully explains the long duration for model inference, as those new versions of tensorflow defaulted to eager execution (very slow), whereas older versions did not.

Also, you had an old version of scCODA (0.1.1) installed in the dependency list that you sent me. Neither `rel_abundance_dispersion_plot` nor automatic reference selection were implemented in that version. The latest version has both these features.

I hope this solves all issues!
