### ISSUE TITLE
MCMC reproducibility

### ISSUE THREAD

**Issue by orrzor** [theislab/scCODA#38]
Hi scCODA team,
Thanks for creating this great algorithm. I have a question on MCMC reproducibility. I am running the following model:
```model_nb = mod.CompositionalAnalysis(data_nb, formula="C(MYCN, Treatment('non-amplified'))", reference_cell_type="Endothelial")```
<img width="601" alt="Screen Shot 2021-09-20 at 2 53 23 PM" src="https://user-images.githubusercontent.com/3698449/134058279-d13cfbcd-450a-4c4e-bcc2-40f6a017890b.png">

When I run the model sampling two separate times, I get slight disagreements in what effects are credible. Below, in one run the stroma cells show up as credible and in another run they show up as not credible. 
<img width="494" alt="Screen Shot 2021-09-20 at 2 45 57 PM" src="https://user-images.githubusercontent.com/3698449/134058384-d0f6a96d-f735-4d43-8111-fd3148e421f3.png">
<img width="480" alt="Screen Shot 2021-09-20 at 2 46 21 PM" src="https://user-images.githubusercontent.com/3698449/134058387-ddd100a9-3fa8-4092-a772-c364b7af948a.png">

Do you have recommendations on what to do in this case? I assume these effects are at the borderline of being credible. Is there a random seed I should set to get reproducible MCMC? And do you have any suggestions on setting the false discovery rate in a systematic manner? Thank you so much! Best, Orr

**Comment by johannesostner** [comment]
Hello Orr,

two different runs of scCODA can indeed lead to slight deviations in the credible effects due to randomness introduced by the MCMC sampling. As you pointed out correctly, the Stroma cells are likely at the border of credibility. 
To obtain fully reproducible results, you can set the seed for tensorflow with `tf.random.set_seed` before running scCODA. You can also set numpy's seed with `np.random.seed`, although this should not be necessary.

In the same way as a frequentist test, the false discovery rate defines the sensitivity of your analysis. Higher FDR will lead to more credible effects, but also a higher chance of false positive results. 
There is no exact guideline on how large the nominal FDR should be, but values between 0.05 and 0.2 are reasonable. The only recommendation I can give is that for small sample sizes, you might want to increase the FDR level to obtain credible results at all, but in your case (57 samples), the default of 0.05 should be fine.

I hope that this answers your questions!

**Comment by orrzor** [comment]
Hi Johannes,
Thanks so much for your quick help! All your points make sense to me, and I appreciate the advice. Best of luck with the review process for scCODA. Best, Orr
