### ISSUE TITLE
Can this be used for differential expression or abundance analysis in non-single celled data (e.g., metagenomics/transcriptomics)?

### ISSUE THREAD

**Issue by jolespin** [theislab/scCODA#44]
I've been incorporating CoDA-valid methodologies in my workflows ever since I realized the caveats of using relative abundance. There's not many packages that implement CoDA versions of differential expression/abundance other than [ALDEx[2]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4030730/), [ANCOM[-BC]](https://www.nature.com/articles/s41467-020-17041-7), and [Songbird](https://www.nature.com/articles/s41467-019-10656-5).  

**Are there any assumptions about the data that would render `scCODA` invalid for 1) non single-celled transcriptomics in one species; 2) metagenomics; or 3) metatranscriptomics?** 

Regardless, thank you for writing this software as I've been wanting to learn how to use `tensorflow_probability` for quite some time and your code is very organized to follow logically.  Most of the tutorials I come across are for image recognition.

**Comment by johannesostner** [comment]
Hi Josh,
thanks for the kind words, I'm happy that you find scCODA useful!

scCODA only assumes that the data is compositional and that one feature (e.g. cell type) exists that is unaffected by the covariates and can be used as a reference, nothing unique to single-cell abundance data.
Indeed, most ideas for scCODA are taken from amplicon sequencing analysis, and I have successfully used it on microbial abundance data before (check out [this paper](https://www.frontiersin.org/articles/10.3389/fgene.2021.766405/full) if you're interested). 
So I generally see no problems with applying scCODA to relative abundance data from other sources as well, as long as you are sure that the data is compositional. The only bottleneck might be performance - I know that scCODA becomes quite memory-hungry for larger datasets.

**Comment by jolespin** [comment]
Thanks for the explanation and the link out. Your mention that cell types are the features had me look again at the tutorial. 

I have a few minor follow up questions:
1) Is it typical in single celled datasets to use cell type as features instead of genes? (Im new to single celled analysis and coming from microbial ecology)

2) If you wanted to look at differential abundant genes between cell types relative to a treatment group of patients, how would you structure your counts table? 

That is, would the dataframe be (sample, cell type) for index and genes as columns or sample as index and (cell type, gene) as columns? 


3) When choosing a reference feature using a data driven approach, do you typically choose the feature that is highly prevalent and has the lowest variance across samples after a CLR transform? 

Also, since a reference feature is needed, this seems like a great opportunity for spike-ins.

**Comment by johannesostner** [comment]
1. Looking at differential abundance of cell types instead of genes is a rather new way of analyzing scRNA-seq datasets, as the number of cells required for this is rather large (you should have multiple samples with at least several hundred cells each). This is also why we emphasised having a method that can deal with very low sample sizes, as this was a major limitation of ANCOM, ALDEx2, or other CoDa methods.
Differential gene expression is the more "classical" approach that has been around for longer and is usually done with DeSeq2 or edgeR (both are not strictly compositional, but have normalization steps that accomplish similar things). It's not 100% established whether gene expression data is strictly relative or not, and I also have no definitive answer to that. Meanwhile, the number of cells per sample is clearly limited by the technology, which prompts CoDa methods.

2. The big difference between gene expression and cell type abundance is the structure of the counts table. Gene expression requires a (cell:gene) table, where the treatment would be a covariate. You could also look at differential gene expression between cell types though, if you consider the cell type as your covariate.
For cell type abundance, your table will be (sample:cell type), and again the treatment as a covariate.

3. We usually choose the feature with the least dispersion over all samples that is also present in more than 90% of samples. This is only a heuristic, though, and you might want to play around with it. Also, you're 100% correct about spike-ins. If you have a cell type where abundance is controlled by spike-ins, then it is a good reference.

I hope that this answers your questions, I'm always happy to discuss more!
