### ISSUE TITLE
Influence of subtypes present in the dataset

### ISSUE THREAD

**Issue by auesro** [theislab/scCODA#57]
Hi,

This is more of a question than a bug. If I should post it somewhere else, please let me know.

I am doing some tests with scCODA and was wondering about the relevance of the number of "populations" included in the dataset. Say I originally have 20 groups (=clusters) and 2 conditions and find no compositional difference between conditions. What influence would it make to subset my dataset to a lower number of groups (e.g. removing 2 groups of less related cells)?

Thanks,

A

**Comment by johannesostner** [comment]
Yes, exactly. This is simply due to the nature of compositional data, as all populations are correlated (i.e. increasing the share of one population decreases the share of all others). If you remove one population, the share of all other populations will increase, but not necessarily by the same amount in both conditions, as you removed a different share in each sample.

Also due to the low number of samples, one outlier could have quite a large impact on the end result.

My suggestion would be to simply take a look at the result after removing the two populations and see if some cell types are differentially abundant then.

**Comment by auesro** [comment]
Thanks a lot, @johannesostner, very insightful!
